### 1. Login
# @name login
POST {{server}}/api/{{version}}/{{loginEndpoint}}
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}"
}

### Get by Id
GET {{server}}/api/{{version}}/iam/users/019d6932-e551-783b-a408-f6ee1e041e96
Authorization: Bearer {{token}}

### Get Users by CustomerId
GET {{server}}/api/{{version}}/iam/users/by-customer/00000000-0000-0000-0000-000000000001
Authorization: Bearer {{token}}
